project:
  type: website
  output-dir: docs

website:
    title: "Ella Stookey"
    navbar:
      background: primary
      left:
        - href: index.qmd
          text: Home
        - posts.qmd
        - documents.qmd

format:
  html:
    theme: 
      - lux
      - styles.scss
    page-layout: full

editor: visual
