project:
  type: website
  output-dir: docs

website:
    title: "Ella Stookey"
    navbar:
      background: primary
      left:
        - href: index.qmd
          text: Home
        - about.qmd
        - documents.qmd
        - posts.qmd

format:
  html:
    theme: lux
    css: styles.css
    page-layout: full

editor: visual
